#-- Colours --#
#Light mode colours
LIGHT_BACKGROUND = "#F8FAFC"
LIGHT_SECONDARY_BACKGROUND = "#FFFFFF"
LIGHT_SIDEBAR = "#E5E7EB"
LIGHT_PRIMARY_ACCENT = "#4F9DFF"
LIGHT_ACCENT_HOVER = "#3A8AF0"
LIGHT_SUCCESS = "#22C55E"
LIGHT_WARNING = "#F59E0B"
LIGHT_ERROR = "#EF4444"
LIGHT_MAIN_TEXT = "#1F2937"
LIGHT_SECONDARY_TEXT = "#6B7280"
LIGHT_BORDER = "#D1D5DB"
LIGHT_DISABLED = "#9CA3AF"
LIGHT_SUCCESS_HOVER = "#1FB155"
LIGHT_SIDEBAR_HOVER = "#D3D5D8"
LIGHT_ERROR_HOVER = "#D23B3B"


# Dark mode colour
DARK_BACKGROUND = "#1E1E1E"
DARK_SECONDARY_BACKGROUND = "#2B2B2B"
DARK_SIDEBAR = "#252526"
DARK_PRIMARY_ACCENT = "#66B2FF"
DARK_ACCENT_HOVER = "#4FA3FF"
DARK_SUCCESS = "#0E662F"
DARK_WARNING = "#FBBF24"
DARK_ERROR = "#F87171"
DARK_MAIN_TEXT = "#F3F4F6"
DARK_SECONDARY_TEXT = "#B3B3B3"
DARK_BORDER = "#404040"
DARK_DISABLED = "#6B7280"


#-- Fonts --#
# Font Family
FONT_FAMILY = "Segoe UI"
MONOSPACE_FONT = "Consolas"

# Titles
FONT_TITLE = (FONT_FAMILY, 28, "bold")
FONT_SUBTITLE = (FONT_FAMILY, 20, "bold")

# Headings
FONT_HEADING = (FONT_FAMILY, 16, "bold")
FONT_SUBHEADING = (FONT_FAMILY, 14, "bold")

# Standard Text
FONT_NORMAL = (FONT_FAMILY, 11)
FONT_SMALL = (FONT_FAMILY, 10)
FONT_TINY = (FONT_FAMILY, 9)

# Buttons
FONT_BUTTON = (FONT_FAMILY, 11, "bold")
FONT_BUTTON_SMALL = (FONT_FAMILY, 10)

# Labels
FONT_LABEL = (FONT_FAMILY, 11)
FONT_LABEL_BOLD = (FONT_FAMILY, 11, "bold")

# Text Entry
FONT_ENTRY = (FONT_FAMILY, 11)


#--Form Score Calculation --#
HALF_LIFE_DAYS = 60
MIN_OPPONENT_FACTOR = 0.8
DEFAULT_PARTNER_FACTOR = 1


#-- Recommeded Team --#
FORM_THRESHOLD = 0.05
PAIRS_PER_TEAM = 2